apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: documentdb-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 256Mi
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: documentdb
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: documentdb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: documentdb
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: documentdb
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: documentdb
      spec:
        containers:
        - image: clameater14/resumeholic-demo:documentdb
          imagePullPolicy: IfNotPresent
          name: documentdb
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/documentdb
            name: storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: documentdb-pvc
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: documentservice
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: documentservice
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: documentservice
      spec:
        containers:
        - env:
          - name: DB_URL
            value: documentdb:3306
          - name: KUBEMQ_ADDRESS
            value: 10.0.9.238:50000
          image: clameater14/resumeholic-demo:documentservice
          imagePullPolicy: Always
          name: documentservice
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: personalinfoheaderdb-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 256Mi
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: personalinfoheaderdb
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: personalinfoheaderdb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: personalinfoheaderdb
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: personalinfoheaderdb
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: personalinfoheaderdb
      spec:
        containers:
        - image: clameater14/resumeholic-demo:personalinfoheaderdb
          imagePullPolicy: IfNotPresent
          name: personalinfoheaderdb
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/personalinfoheaderdb
            name: storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: personalinfoheaderdb-pvc
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: personalinfoheaderservice
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: personalinfoheaderservice
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: personalinfoheaderservice
      spec:
        containers:
        - env:
          - name: DB_URL
            value: personalinfoheaderdb:3306
          - name: KUBEMQ_ADDRESS
            value: 10.0.9.238:50000
          image: clameater14/resumeholic-demo:personalinfoheaderservice
          imagePullPolicy: Always
          name: personalinfoheaderservice
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: userdb-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 256Mi
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: userdb
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: userdb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: userdb
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: userdb
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: userdb
      spec:
        containers:
        - image: clameater14/resumeholic-demo:userdb
          imagePullPolicy: IfNotPresent
          name: userdb
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/userdb
            name: storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: userdb-pvc
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: frontend
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: frontend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: frontend
      spec:
        containers:
        - env:
          - name: DOCUMENT_SERVICE
            value: documentservice:80
          - name: PERSONAL_INFO_HEADER_SERVICE
            value: personalinfoheaderservice:80
          - name: DB_URL
            value: userdb:3306
          image: clameater14/resumeholic-demo:frontend
          imagePullPolicy: Always
          name: frontend
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: documentservice
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: documentservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: personalinfoheaderservice
  spec:
    internalTrafficPolicy: Cluster
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: personalinfoheaderservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: frontend
  spec:
    allocateLoadBalancerNodePorts: true
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: frontend
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer: {}
kind: List
metadata: {}
